CE USART: src/MCU/usart3.c File Reference
usart3.c File Reference
USART Driver implementation for SerialPort3.
#include "MCU/usart3.h"
Macros
#define UART_DIV_SAMPLING16(_PCLK_, _BAUD_) (((_PCLK_)*25U)/(4U*(_BAUD_)))
#define UART_DIVMANT_SAMPLING16(_PCLK_, _BAUD_) (UART_DIV_SAMPLING16((_PCLK_), (_BAUD_))/100U)
#define UART_DIVFRAQ_SAMPLING16(_PCLK_, _BAUD_) (((UART_DIV_SAMPLING16((_PCLK_), (_BAUD_)) - (UART_DIVMANT_SAMPLING16((_PCLK_), (_BAUD_)) * 100U)) * 16U + 50U) / 100U)
#define UART_DIV_SAMPLING8(_PCLK_, _BAUD_) (((_PCLK_)*25U)/(2U*(_BAUD_)))
#define UART_DIVMANT_SAMPLING8(_PCLK_, _BAUD_) (UART_DIV_SAMPLING8((_PCLK_), (_BAUD_))/100U)
#define UART_DIVFRAQ_SAMPLING8(_PCLK_, _BAUD_) (((UART_DIV_SAMPLING8((_PCLK_), (_BAUD_)) - (UART_DIVMANT_SAMPLING8((_PCLK_), (_BAUD_)) * 100U)) * 8U + 50U) / 100U)
#define UART_BRR_SAMPLING16(_PCLK_, _BAUD_)
These macros set that fractional buad rate this has been taken from the STM provided HAL.
#define UART_BRR_SAMPLING8(_PCLK_, _BAUD_)
These macros set that fractional buad rate this has been taken from the STM provided HAL.
Functions
static uint_fast8_t IsOpen (void)
Return the status of the Interface.
static void Close (void)
Closes open interface.
static uint_fast8_t IsWriteBusy (void)
Checks if write is in progress.
static uint_fast8_t RxBufferHasData (void)
Checks if there is data to read.
static SerialResult_t Open (uint32_t baudrate)
Open serial interface with specified baudrate.
static SerialResult_t SendByte (uint8_t source)
Send one byte over the interface.
static SerialResult_t GetByte (uint8_t *destination)
Retrieve byte from interface.
static SerialResult_t SendString (const char *source)
Send string over interface.
static SerialResult_t SendArray (const uint8_t *source, uint32_t length)
Send string over interface.
Variables
static uint_fast8_t IsOpenFlag = FALSE
Internal flag for open status.
SerialInterface SerialPort3
Initializing SerialPort3.
Detailed Description
USART Driver implementation for SerialPort3.
Author
Matthew Philyaw (matth.nosp@m.ew.p.nosp@m.hilya.nosp@m.w@gm.nosp@m.ail.c.nosp@m.om)
Definition in file usart3.c.
Macro Definition Documentation
#define UART_BRR_SAMPLING16 (_PCLK_, _BAUD_)
Value:
(((UART_DIVMANT_SAMPLING16((_PCLK_), (_BAUD_)) << 4U) + \
                                                        (UART_DIVFRAQ_SAMPLING16((_PCLK_), (_BAUD_)) & 0xF0U)) + \
                                                        (UART_DIVFRAQ_SAMPLING16((_PCLK_), (_BAUD_)) & 0x0FU))
These macros set that fractional buad rate this has been taken from the STM provided HAL.
Definition at line 22 of file usart3.c.
Referenced by Open().
#define UART_BRR_SAMPLING8 (_PCLK_, _BAUD_)
Value:
(((UART_DIVMANT_SAMPLING8((_PCLK_), (_BAUD_)) << 4U) + \
                                                        ((UART_DIVFRAQ_SAMPLING8((_PCLK_), (_BAUD_)) & 0xF8U) << 1U)) + \
                                                        (UART_DIVFRAQ_SAMPLING8((_PCLK_), (_BAUD_)) & 0x07U))
These macros set that fractional buad rate this has been taken from the STM provided HAL.
Definition at line 30 of file usart3.c.
Referenced by Open().
Function Documentation
static SerialResult_t GetByte (uint8_t * destination) static
Retrieve byte from interface.
Parameters
[out] destination is the pointer to put the byte into
Returns
SERIAL_SUCCESS -> Byte successfully read without errors
SERIAL_CLOSE -> Interface is closed and nothing is done
SERIAL_INVALID_PARAMETER -> destination is a null pointer
SERIAL_NO_DATA -> No data to read from interface
SERIAL_OVER_RUN -> Byte in data register is valid, but next byte to be shifted in is being overwritten (I.E not reading fast enough)
SERIAL_FRAMING_ERROR -> Byte in data register is likely junk and issue with buadrate or other parameters thus interface is no longer in sync
SERIAL_PARITY_ERROR -> Byte in data register is likely junk and parity check failed
SERIAL_NOISE_ERROR -> Byte is data register is likely junk and noise was detected on the line
Definition at line 151 of file usart3.c.
References IsOpenFlag, RxBufferHasData(), SERIAL_CLOSED, SERIAL_FRAMING_ERROR, SERIAL_INVALID_PARAMETER, SERIAL_LINE_BREAK_ERROR, SERIAL_NO_DATA, SERIAL_NOISE_ERROR, SERIAL_OVER_RUN, SERIAL_PARITY_ERROR, and SERIAL_SUCCESS.
static uint_fast8_t IsOpen (void) static
Return the status of the Interface.
Returns
1 -> Open
0 -> Closed
Definition at line 45 of file usart3.c.
References IsOpenFlag.
static uint_fast8_t IsWriteBusy (void) static
Checks if write is in progress.
Returns
1 -> Write in progress
0 -> Interface ready
Definition at line 63 of file usart3.c.
Referenced by SendByte().
static SerialResult_t Open (uint32_t baudrate) static
Open serial interface with specified baudrate.
Parameters
baudrate is the desired baudrate
Returns
SERIAL_FAIL -> interface is open, nothing to do
SERIAL_SUCCESS -> interface was opened and initialized
Definition at line 86 of file usart3.c.
References IsOpenFlag, SERIAL_FAIL, SERIAL_SUCCESS, UART_BRR_SAMPLING16, and UART_BRR_SAMPLING8.
static uint_fast8_t RxBufferHasData (void) static
Checks if there is data to read.
Returns
1 -> Data to read
0 -> No data to read
Definition at line 74 of file usart3.c.
Referenced by GetByte().
static SerialResult_t SendArray (const uint8_t * source, uint32_t length) static
Send string over interface.
Parameters
source pointer to byte array
length of the byte array
Returns
SERIAL_CLOSED -> Interface is closed and nothing is done
SERIAL_INVALID_PARAMETER -> source pointer is a null pointer
SERIAL_FAIL -> SendByte failed
SERIAL_SUCCESS -> String has been sent
Definition at line 229 of file usart3.c.
References IsOpenFlag, SendByte(), SERIAL_CLOSED, SERIAL_FAIL, SERIAL_INVALID_PARAMETER, and SERIAL_SUCCESS.
static SerialResult_t SendByte (uint8_t source) static
Send one byte over the interface.
Parameters
source is the byte to send
Returns
SERIAL_CLOSED -> Interface is closed and nothing is done
SERIAL_SUCCESS -> Byte has been sent
Definition at line 125 of file usart3.c.
References IsOpenFlag, IsWriteBusy(), SERIAL_CLOSED, and SERIAL_SUCCESS.
Referenced by SendArray(), and SendString().
static SerialResult_t SendString (const char * source) static
Send string over interface.
Parameters
source pointer to string
Returns
SERIAL_CLOSED -> Interface is closed and nothing is done
SERIAL_INVALID_PARAMETER -> source pointer is a null pointer
SERIAL_FAIL -> SendByte failed
SERIAL_SUCCESS -> String has been sent
Definition at line 199 of file usart3.c.
References IsOpenFlag, SendByte(), SERIAL_CLOSED, SERIAL_FAIL, SERIAL_INVALID_PARAMETER, and SERIAL_SUCCESS.
Variable Documentation
SerialInterface SerialPort3
Initial value:
= {
  IsOpen,
  RxBufferHasData,
  Open,
  Close,
  SendByte,
  SendString,
  SendArray,
  GetByte
}
Initializing SerialPort3.
Definition at line 251 of file usart3.c.